export const SETTINGS_CHANGED = 'settings/changed'
export const DIRECTION_CHANGED = 'direction/changed'
export const GAME_STARTED = 'game/started'
export const GAME_FINISHED = 'game/finished'
export const SNAKE_MOVED = 'snake/moved'
